#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)

#=================================================
# STANDARD REMOVE
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
fi

# Stop and remove the systemd service
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=1
ynh_remove_systemd_config

# Remove the app directory securely
ynh_script_progression --message="Removing app main directory..." --weight=1
ynh_secure_remove --file="$final_path"

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
	ynh_script_progression --message="Removing app data directory..." --weight=1
	ynh_secure_remove --file="$data_dir"
fi

# Remove the dedicated system user
ynh_script_progression --message="Removing the dedicated system user..." --weight=1
ynh_system_user_delete --username=$app

# Remove the app-specific logrotate config
ynh_script_progression --message="Removing logrotate configuration..." --weight=1
ynh_remove_logrotate

# Remove the dedicated NGINX config
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1
ynh_remove_nginx_config

# Remove Node.js
ynh_script_progression --message="Removing Node.js..." --weight=1
ynh_remove_nodejs

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --weight=1