#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_script_progression --message="Validating restoration parameters..." --weight=1

test ! -d $final_path || ynh_die --message="There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================

# Restore the app main directory
ynh_script_progression --message="Restoring the app main directory..." --weight=1
ynh_restore_file --origin_path="$final_path"

chmod 750 "$final_path"
chown -R $app:www-data "$final_path"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

ynh_script_progression --message="Recreating the dedicated system user..." --weight=1
ynh_system_user_create --username=$app --home_dir="$final_path"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================

ynh_script_progression --message="Restoring the data directory..." --weight=1
ynh_restore_file --origin_path="$data_dir"

mkdir -p $data_dir
chown -R $app:$app $data_dir
chmod 750 $data_dir

#=================================================
# SPECIFIC RESTORATION
#=================================================

# Install Node.js
ynh_script_progression --message="Reinstalling Node.js..." --weight=5
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=18

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_script_progression --message="Restoring the NGINX web server configuration..." --weight=1
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE SYSTEMD
#=================================================

ynh_script_progression --message="Restoring the systemd configuration..." --weight=1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

#=================================================
# RESTORE LOGROTATE
#=================================================

ynh_script_progression --message="Restoring the logrotate configuration..." --weight=1
ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app --description="Contacts Libres CNT-AIT" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression --message="Starting a systemd service..." --weight=1
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX
#=================================================

ynh_script_progression --message="Reloading NGINX web server..." --weight=1
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --weight=1